#! /usr/bin/env zsh

function every {
  ##
  ## Iterate over $list and match every element with $predicate. Return `true`
  ## if every element of the $list matches with $predicate. Otherwise, return `false`.
  ##

  local counter=0
  local -a list=(${@:2})
  local predicate=${@:1:1}
  local size=${#list}

  foreach e ($list) { [[ $e =~ $predicate ]] && (( counter+=1 )) }

  # echo "list: ($list)"
  # echo "counter: $counter"
  # echo "size: $size"

  [[ $counter -eq $size ]]
}

function all {
  ##
  ## Pass each element of $list to $predicate. Return `true` if $predicate
  ## never returns `false`. Otherwise, return `false`.
  ##

  local counter=0
  local -a list=(${@:2})
  local predicate=${@:1:1}
  local size=${#list}

  foreach e ($list) { $predicate $e && (( counter+=1 )) }

  # echo "list: ($list)"
  # echo "counter: $counter"
  # echo "size: $size"

  [[ $counter -eq $size ]]
}

function main TRAPEXIT {

  local -a list=(1 1 1)
  local val=1

  local f() { [[ $1 -le $val ]] }

  if { every $val $list } {
    echo "All values in the list is equal to $val."
  } else {
    echo "Some values in the list is not equal to $val."
  }

  if { all f $list } {
    echo "All values in the list is less then or equal to $val."
  } else {
    echo "Some values in the list is not less then or equal to $val."
  }
}

