
server: bundle exec rails server --binding 192.168.0.10 --port 8080
css: bundle exec rails tailwindcss:watch
tags: /usr/bin/zsh -c "while ( inotifywait --recursive --include='.*rb|.*js' --event=modify,create $PWD ) { ctags --recurse --languages=Ruby,JavaScript --exclude=vendor --excmd=number --fields=Kzn }"

