[package]
name = "questions-answers"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.2", features = ["full"] }
warp = "0.3.7"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
