
source 'https://rubygems.org'

gem 'rails', '~>7.2.1'
gem 'sprockets-rails'
gem 'sqlite3'
gem 'puma'
gem 'importmap-rails'
gem 'bcrypt'
gem 'ostruct'
gem 'haml-rails'
gem 'dartsass-sprockets'
gem 'action_policy'
gem 'tzinfo-data'

gem 'debug', require: 'debug/prelude'

gem 'tailwindcss-rails', '~>3.3.1'

group :production do
end

group :development, :test do
  gem 'rspec-rails'
end

group :development do
  gem 'foreman'
end

group :test do
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'capybara'
  gem 'cuprite'
end

