
source 'https://rubygems.org'

##
## Authorization framework for Ruby/Rails applications
##
## • [palkan/action_policy: Authorization framework for Ruby/Rails applications](https://github.com/palkan/action_policy)
##
## • [Action Policy: authorization framework for Ruby/Rails applications](https://actionpolicy.evilmartians.io)
##
gem 'action_policy'

##
## bcrypt-ruby is a Ruby binding for the OpenBSD bcrypt() password hashing
## algorithm, allowing you to easily store a secure hash of your users' passwords.
##
## Allows to use Active Model has_secure_password.
##
## • [Active Model Basics — Ruby on Rails Guides](https://guides.rubyonrails.org/active_model_basics.html#securepassword)
##
## • [bcrypt-ruby/bcrypt-ruby: bcrypt-ruby is a Ruby binding for the OpenBSD bcrypt() password hashing algorithm, allowing you to easily store a secure hash of your users' passwords.](https://github.com/bcrypt-ruby/bcrypt-ruby)
##
gem 'bcrypt'

##
## Debugging functionality for Ruby
##
## • [ruby/debug: Debugging functionality for Ruby](https://github.com/ruby/debug)
##
## • [Debugging Rails Applications — Ruby on Rails Guides](https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem)
##
gem 'debug', require: 'debug/prelude'

##
## Haml-rails provides Haml generators for Rails 5, 6, 7, and 8. It also enables
## Haml as the templating engine for you, so you don't have to screw around in your
## own application.rb when your Gemfile already clearly indicated what templating
## engine you have installed
##
## [haml/haml-rails: let your Gemfile do the talking](https://github.com/haml/haml-rails)
##
gem 'haml-rails'

##
## Use ESM with importmap to manage modern JavaScript in Rails without transpiling or bundling.
##
## [rails/importmap-rails: Use ESM with importmap to manage modern JavaScript in Rails without transpiling or bundling.](https://github.com/rails/importmap-rails)
##
gem 'importmap-rails'

##
## Jbuilder: generate JSON objects with a Builder-style DSL
##
## [rails/jbuilder: Jbuilder: generate JSON objects with a Builder-style DSL](https://github.com/rails/jbuilder)
##
gem 'jbuilder'

##
## OpenStruct implementation
##
## An OpenStruct is a data structure, similar to a Hash, that allows the
## definition of arbitrary attributes with their accompanying values. This is
## accomplished by using Ruby's metaprogramming to define methods on the class
## itself.
##
## [ruby/ostruct: OpenStruct implementation](https://github.com/ruby/ostruct)
##
## The gem was migrated from stdlib to bundled gems at Ruby 3.5. It needs to
## manually add it as a dependency in order to prevent the warning message.
##
## Details:
##
## [Feature #20309: Bundled gems for Ruby 3.5 - Ruby master - Ruby Issue Tracking System](https://bugs.ruby-lang.org/issues/20309)
##
gem 'ostruct'

##
## Deliver assets for Rails
##
## [rails/propshaft: Deliver assets for Rails](https://github.com/rails/propshaft)
##
gem 'propshaft'

##
## A Ruby/Rack web server built for parallelism
##
## [puma/puma: A Ruby/Rack web server built for parallelism](https://github.com/puma/puma)
##
gem 'puma'

##
## Ruby on Rails
##
## [rails/rails: Ruby on Rails](https://github.com/rails/rails)
##
gem 'rails', '~>8.0.0'

##
## Ruby bindings for the SQLite3 embedded database
##
## [sparklemotion/sqlite3-ruby: Ruby bindings for the SQLite3 embedded database](https://github.com/sparklemotion/sqlite3-ruby)
##
gem 'sqlite3'

##
## Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
##
## • [hotwired/stimulus: A modest JavaScript framework for the HTML you already have](https://github.com/hotwired/stimulus)
##
## • [Stimulus: A modest JavaScript framework for the HTML you already have.](https://stimulus.hotwired.dev)
##
gem 'stimulus-rails'

# gem 'tzinfo-data'

##
## Tailwind CSS is a utility-first CSS framework packed with classes like flex,
## pt-4, text-center and rotate-90 that can be composed to build any design,
## directly in your markup.
##
## [rails/tailwindcss-rails](https://github.com/rails/tailwindcss-rails)
##
gem 'tailwindcss-rails', '3.3.1'

##
## Use Turbo in your Ruby on Rails app
##
## [hotwired/turbo-rails: Use Turbo in your Ruby on Rails app](https://github.com/hotwired/turbo-rails)
##
gem 'turbo-rails'

group :production do
end

group :development, :test do
  ##
  ## This gem brings back assigns to your controller tests as well as
  ## assert_template to both controller and integration tests.
  ##
  ## [rails/rails-controller-testing: Brings back `assigns` and `assert_template` to your Rails tests](https://github.com/rails/rails-controller-testing)
  ##
  gem 'rails-controller-testing'

  ##
  ## RSpec::ActiveModel::Mocks provides tools for testing ActiveModel classes.
  ##
  ## [rspec/rspec-activemodel-mocks: Add stub_model and mock_model to rspec-mocks](https://github.com/rspec/rspec-activemodel-mocks)
  ##
  gem 'rspec-activemodel-mocks'

  ##
  ## rspec-rails brings the RSpec testing framework to Ruby on Rails as a drop-in
  ## alternative to its default testing framework, Minitest.
  ##
  ## [rspec/rspec-rails: RSpec for Rails 7+](https://github.com/rspec/rspec-rails)
  ##
  gem 'rspec-rails'
end

group :development do
  ##
  ## Manage Procfile-based applications
  ##
  ## [ddollar/foreman: Manage Procfile-based applications](https://github.com/ddollar/foreman)
  ##
  gem 'foreman'
end

group :test do
  ##
  ## Acceptance test framework for web applications
  ##
  ## [teamcapybara/capybara: Acceptance test framework for web applications](https://github.com/teamcapybara/capybara)
  ##
  gem 'capybara'

  ##
  ## Rails Generators for Cucumber with special support for Capybara and DatabaseCleaner
  ##
  ## [cucumber/cucumber-rails: Rails Generators for Cucumber with special support for Capybara and DatabaseCleaner](https://github.com/cucumber/cucumber-rails)
  ##
  gem 'cucumber-rails', require: false

  ##
  ## Headless Chrome/Chromium driver for Capybara
  ##
  ## [rubycdp/cuprite: Headless Chrome/Chromium driver for Capybara](https://github.com/rubycdp/cuprite)
  ##
  gem 'cuprite'

  ##
  ## Strategies for cleaning databases in Ruby. Can be used to ensure a clean state for testing.
  ##
  ## [DatabaseCleaner/database_cleaner: Strategies for cleaning databases in Ruby. Can be used to ensure a clean state for testing.](https://github.com/DatabaseCleaner/database_cleaner)
  ##
  gem 'database_cleaner'
end

