
source 'https://rubygems.org'

gem 'rails'
gem 'sprockets-rails'
gem 'sqlite3'
gem 'puma'
gem 'importmap-rails'
gem 'turbo-rails'
gem 'stimulus-rails'
gem 'bcrypt'
gem 'ostruct'
gem 'haml-rails'
gem 'dartsass-sprockets'
gem 'action_policy'

group :development, :test do
  gem 'debug', require: 'debug/prelude'
  gem 'tailwindcss-rails'
  gem 'rspec-rails'
end

group :development do
  gem 'foreman'
  gem 'authentication-zero'
end

group :test do
  gem 'cucumber-rails', require: false
  gem 'database_cleaner'
  gem 'capybara'
  gem 'cuprite'
end

