# :::sample:::

.PHONY: one three four five six fin
.DEFAULT_GOAL = fin

one:
	@echo ok!

two:
	@echo ok too!

three:
	@echo ok free!

four:
	@echo ok for!

five:
	@echo ok fine!

six:
	@echo ok sex!

fin: one two three four five six
	@echo fin!

