
services:
  main:
    image: "ticketee.ru:5000/ticketee-main"
    build:
      context: .
      network: host
      target: main
    networks:
      main:
        ipv4_address: "10.0.45.151"
    volumes:
      - type: volume
        source: ticketee-db
        target: "/home/ticketee/app/storage/"
        # target: "/home/ticketee/app/storage/production.sqlite3"
      # - type: bind
      #   source: "/home/user/.workspace/playground/rails/ticketee/storage/production.sqlite3"
      #   target: "/home/ticketee/app/storage/production.sqlite3"
        # bind:
        #   propagation: shared
      - type: bind
        source: "/home/user/.workspace/playground/rails/ticketee/log/production.log"
        target: "/home/ticketee/app/log/production.log"
        # bind:
        #   propagation: shared

  proxy:
    image: "ticketee.ru:5000/ticketee-proxy"
    build:
      context: .
      network: host
      target: proxy
    networks:
      main:
        ipv4_address: "10.0.45.141"
    ports:
      - "80:80"

volumes:
  ticketee-db:
    name: ticketee.db

networks:
  main:
    name: ticketee.net
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: "docker-ticketee"
    ipam:
      config:
        - subnet: "10.0.45.0/24"
          ip_range: "10.0.45.128/25"
          gateway: "10.0.45.1"

